### ISSUE TITLE
Figlet: Remove unnessecary new lines

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/simple-discord-bot#1]
In the figlet command it may under some certain circumstances add unneeded newlines:
![Figlet cmd in use](https://i.neat.moe/56a27c0388fe2be9.png)

**Comment by fuerbringer** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim

:thinking:

**Comment by Hoi15A** [comment]
TIL that exists, neat
