### ISSUE TITLE
Usage logging

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/simple-discord-bot#11]
Doesnt need to be fancy, as long as it helps figure out:
- Where it crashes
- If people are messing with it

**Comment by fuerbringer** [comment]
I recommend using Winston. See how I used it in my bot [here](https://github.com/fuerbringer/tldr-telegram/pull/11/files).

**Comment by Hoi15A** [comment]
fea4b6eaadc0be3db63816c193b54af022ad1219 Added the proper djs error event which should take care of most stupid shit. This issue is old and I will probably not get around to it nor do I have much of a plan on how to do it so I'll close it for now.
