### ISSUE TITLE
Figlet command: Error on empty output

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/simple-discord-bot#12]
If a user inputs a string that results in empty output, send an error message instead of an empty codeblock:
<img src="https://i.neat.moe/ef48a54b634db391.png">

**Comment by waspothegreat** [comment]
ok then :FeelsWeirdMan:

**Comment by Hoi15A** [comment]
Also on flags that dont exist 
![image](https://user-images.githubusercontent.com/10325316/50574910-0fcf4780-0df2-11e9-8a02-eee2f1f1c3bc.png)
