### ISSUE TITLE
Commands suddenly trigger multiple times

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/simple-discord-bot#35]
After a certain amount of time commands start to trigger multiple times (most seen was 3x)
Seems to potentially be an issue with djs disconnecting.

Needs to be looked into more. Addition of usage logging would potentially help

**Comment by Hoi15A** [comment]
(I wanna bet 10 points on the fact that it might be the ready event triggering multiple times https://github.com/Hoi15A/simple-discord-bot/blob/master/index.js#L25)

Note to self: look at that as a possibility

**Comment by waspothegreat** [comment]
It may have to do with that because you usually don't make a command handler on the ready event

**Comment by Froosk** [comment]
what are you talking about? my bot has the command handler on the ready event

**Comment by waspothegreat** [comment]
Well my command handler is separate for my bot

**Comment by Hoi15A** [comment]
Should be fixed now that commands are not loaded on the reload event anymore
